"""Typing text pools organised by category and level (1 = easiest .. 10 = hardest).

Every passage is a single line of plain text (single spaces only) so the
front-end can render it character-by-character without line-wrap surprises.
"""

import random
from datetime import date

CATEGORIES = [
    "General", "English", "Programming", "Science", "Mathematics", "Academic", "Interview",
]

L = {
    "General": {
        1: [
            "the sky is blue and the sun is warm today",
            "a small dog ran across the green field",
            "i like to read books on a quiet afternoon",
            "the cat sleeps on the soft couch all day long",
            "we walk to school together every single morning",
            "the flowers in the garden smell very sweet",
        ],
        2: [
            "a quick brown fox jumps over a lazy dog near the old wooden fence",
            "learning to type well takes a little time and a lot of practice",
            "the new bookstore opens early and closes late every weekday",
            "my favorite season is spring because everything turns green",
            "the train arrives at the station right on time each morning",
            "a warm cup of tea makes any rainy day feel much better",
        ],
        3: [
            "typing is a skill that improves with daily practice, and every student can master it with patience",
            "the library is quiet, well lit, and full of books that you can borrow for free",
            "our team meets every Monday, discusses the plan, and works together until the task is done",
            "she packed her bag, checked the map twice, and left home long before the sun rose",
            "good habits, like exercising and reading, build a strong foundation for a healthy life",
            "the museum opens its doors at nine, and the guided tour starts exactly one hour later",
        ],
        4: [
            "the internet is a powerful tool, but students should always verify the sources they rely on for their research",
            "he woke up early, stretched for a few minutes, and then reviewed his notes before the big exam",
            "success rarely comes overnight; it is built through small, consistent efforts made day after day",
            "the city park offers jogging trails, basketball courts, and a small pond with ducks and swans",
            "before you submit your assignment, read it aloud once, because your ears often catch mistakes your eyes miss",
            "we planned the road trip carefully, booked the rooms in advance, and packed enough snacks for everyone",
        ],
        5: [
            "The 2024 science fair featured 128 projects from 40 schools, and the winning entry used recycled materials to generate clean power.",
            "A good study routine includes short breaks; 25 minutes of focus followed by 5 minutes of rest works well for most students.",
            "The app's latest update (version 3.2) fixed 14 bugs, improved battery life by 20%, and added a dark mode toggle.",
            "Our teacher said: \"Practice every day, even on weekends, and you will see real progress within a month.\"",
            "The marathon covered 42.2 kilometers, climbed 600 meters in elevation, and finished at the old lighthouse on the coast.",
            "By 2030, engineers predict that electric vehicles will account for 60% of all new car sales across the globe.",
        ],
        6: [
            "The average smartphone user checks their device 96 times a day — that is roughly once every ten waking minutes — which is why digital wellness matters more than ever.",
            "In 2023 alone, online learning platforms delivered over 2.5 billion lessons, and the most popular subjects were programming (41%), mathematics (27%), and design (18%).",
            "The bakery opens at 6:30 a.m. and sells an average of 340 loaves daily; its signature sourdough, which bakes for 22 hours, is often sold out by noon.",
            "Recent studies show that students who type notes instead of writing them summarize at 12% higher speed but recall 8% less detail than their handwriting peers.",
            "The new bridge spans 1,540 meters, weighs 92,000 tons, and took 5 years and 7 months to complete at a total cost of $780 million.",
            "Reading for just 20 minutes per day exposes a student to roughly 1.8 million new words per year, dramatically expanding their vocabulary and comprehension.",
        ],
        7: [
            "The 30-story tower houses 210 apartments, a rooftop garden, and a public library on the third floor; the entire building was completed in 8 months using prefabricated panels.",
            "Experts agree that the most effective learners review material four times: once immediately, once after 24 hours, once after one week, and once before the final exam.",
            "The annual report showed revenue of $3.4 million, up 27% from last year, while operating costs rose just 6%, producing the company's strongest profit margin since 2019.",
            "When you organize your workspace, you reduce decision fatigue by up to 30%, which is why top performers keep only a pen, a notebook, and a single monitor on their desk.",
            "The weather station recorded 214 millimeters of rain in 48 hours, an amount equal to half the region's typical yearly total, causing the river to rise 3.7 meters.",
            "Historians estimate that the ancient city covered 12 square kilometers and housed about 45,000 people; its 8-meter walls protected it for more than 500 years.",
        ],
        8: [
            "The marathon tested every discipline: runners downed 2,400 calories of fuel, burned roughly 3,200 calories, drank 5 liters of water, and ran 42.2 kilometers in an average of 4 hours and 12 minutes between the 9 a.m. start and the 3 p.m. cutoff.",
            "Cognitive science demonstrates that spaced repetition outperforms cramming: students who reviewed vocabulary at intervals of 1, 7, and 21 days retained 78% after a month, versus 19% for those who studied in a single session.",
            "Global internet traffic reached 4.6 zettabytes in 2024, and video streaming alone accounted for 65% of that figure; researchers warn that without efficiency gains, data centers could consume 8% of the world's electricity by 2030.",
            "The vintage camera, restored over 14 months, still works perfectly: its 35-millimeter lens captures 12 megapixels, its leather case dates to 1952, and its original price of $89 would equal roughly $940 in today's currency.",
            "An effective morning routine shares one trait across all cultures: it begins slowly. Nutritionists suggest hydrating with 500 milliliters of water, eating protein within 90 minutes, and postponing phone use until after the first 30 minutes of the day.",
            "The engineering team shipped version 8.4 after 340 commits, 18 code reviews, and 2,100 automated tests; the release reduced page-load time by 41% (from 2.3 to 1.35 seconds) and fixed 27 reported issues tracked across 6 different milestones.",
        ],
        9: [
            "Urban forests, occupying just 3% of most cities' land, remove up to 25 tons of carbon dioxide per square kilometer each year; researchers recommend planting 1 native tree for every 3 residents — a ratio met by only 12 of the 50 largest cities surveyed worldwide in 2024.",
            "The international typing championship saw its youngest finalist, a 14-year-old student, hit 218 words per minute on a 10-minute accuracy test; her error rate of 0.3% stunned veteran competitors, who averaged 1.2% errors over the same 60 power words per minute threshold.",
            "Historians trace the modern keyboard to 1874, when the first commercially successful typewriter shipped with 44 keys; by 2024, the average keyboard had grown to 104 keys, but the core QWERTY layout — designed to prevent key jams — has survived more than 150 years of technological change.",
            "A growing body of research links handwriting to memory: participants who wrote notes by hand scored 22% higher on conceptual questions, because the act of writing slows processing and forces the brain to summarize, a mechanism that vanishes when notes are typed verbatim at 65 words per minute.",
            "The ambitious renovation of the old central station, budgeted at $2.1 billion, added 12 new platforms, a 40,000-square-meter shopping hall, and a living green roof spanning 1.8 hectares; officials claim the project will cut commuter transfer times by 25 minutes each way and reduce the building's energy needs by 38%.",
            "In game theory, a Nash equilibrium occurs when no player can improve their outcome by changing strategy alone; economists use this concept to model everything from auction bidding to traffic flow, and the 1994 Nobel Prize in Economic Sciences honored its discovery — a reminder that elegant mathematics often starts with observing how humans actually behave.",
        ],
        10: [
            "At 8:47 a.m. on March 14, the flight controller logged an anomaly: the telemetry stream, 2.4 gigabytes per minute across 6 redundant sensors, reported a 0.7°C drift in the starboard thruster assembly, a value within tolerance but trending outside the model by 31% — triggering an automated review that would take 22 engineers and 6 days to resolve.",
            "Legend says the ancient library of Alexandria aimed to house 'a copy of every book in the world,' and its curators reportedly held ships' manuscripts until scribes transcribed them; modern estimates place its collection between 40,000 and 700,000 scrolls, but the deeper lesson endures: organized knowledge, shared freely, has always been civilization's most powerful accelerant.",
            "The precision watchmaker assembles each movement from 348 components, tolerances measured in microns, over 2.5 weeks of work; of every 1,000 movements produced at the Geneva atelier, only 12 earn the observatory certificate — requiring chronometric accuracy of −4 to +6 seconds per day, sustained across 40 consecutive days and 5 temperature extremes, including a simulated Antarctic night.",
            "In the 1940s, encoder operators broke the German Enigma codes using electromechanical 'bombes' that tested 26 possible rotor positions per second; historians estimate the effort shortened World War II by 2 to 4 years and saved over 14 million lives — a stark demonstration that computational thinking, honed under pressure, reshapes the outcome of human events at a continental scale.",
            "The deepest ocean trench, 10,935 meters below the surface, exerts pressures of 1,086 bars — equivalent to 50 jumbo jets stacked on a single square meter; only 3 crewed missions have reached its floor, fewer than the 12 humans who have walked on the Moon, and each descent carried more computing power to read a single pressure gauge than the Apollo guidance computer carried to navigate the entire lunar landing.",
            "Satellite imagery over the past 35 years shows that global tree cover declined by 137 million hectares — an area larger than South Africa — yet 33 countries saw net reforestation led by community programs; researchers at 14 universities now model these changes at 10-meter resolution, and their 2025 projections suggest that policy shifts alone could restore 45% of the damage by 2060, if nations act within the next decade.",
        ],
    },
    "English": {
        1: [
            "the cat sits on the mat and purrs",
            "a red ball rolled under the wooden table",
            "the birds sing early in the morning",
            "my friend lives next door to the bakery",
            "the lamp glows softly beside the bed",
            "we sing along to our favorite song",
        ],
        2: [
            "the cheerful children played hide and seek among the tall oak trees",
            "a gentle breeze carried the sweet scent of fresh flowers across the garden",
            "the young puppy chewed the old slipper that was left near the stairs",
            "reading a good story before bed helps the mind relax and feel calm",
            "the bright yellow school bus waited patiently at the corner of the street",
            "grandfather told a funny tale about the time he met a raccoon",
        ],
        3: [
            "the old lighthouse stood alone on the rocky cliff, guiding ships through the misty night",
            "she wandered through the crowded market, past stalls of fruit, flowers, and handmade crafts",
            "the gentle rain tapped on the window while the family settled down to watch a movie",
            "curiosity is the quiet engine of learning, and it never runs out of fuel",
            "the village baker rises at dawn, kneads the dough, and fills the street with the smell of warm bread",
            "after the storm passed, the children ran outside and splashed in the puddles with joy",
        ],
        4: [
            "the ocean waves crashed against the shore, then retreated slowly, leaving behind shells and seaweed",
            "patience and persistence are two quiet virtues that often deliver the loudest results",
            "the old woman fed the stray cats every evening, and they waited for her at the garden gate",
            "the mountain path twisted upward through pines and ferns until it opened onto a cloud-covered summit",
            "a single candle in the window tells the neighbors that someone is home and welcome",
            "the experienced teacher explained the difficult idea again, this time with chalk and drawings",
        ],
        5: [
            "The novel begins with a single sentence, yet that one line carries enough tension to hold the reader for the next four hundred pages.",
            "Careful editing transforms a clumsy draft into polished prose; the writer cuts, rewrites, and polishes until every sentence earns its place.",
            "The old sailor recounted his voyages: typhoons off the coast of Japan, nights of dead calm near the equator, and mornings lit by whales surfacing at dawn.",
            "Fiction offers empathy in its purest form, because a reader must willingly inhabit another person's thoughts, fears, and deepest desires.",
            "The silent library, with its towering shelves and the faint smell of old paper, remains one of the most magical places in any town.",
            "Each generation believes its slang is cleverer than the last, and each one is wrong in exactly the same charming way.",
        ],
        6: [
            "The sculpture, carved from a single block of marble over five years, depicts a figure mid-step so lifelike that visitors instinctively step aside to let it pass.",
            "Brevity is the soul of wit, as the old saying goes, but brevity is also hard work: the short essay is often the one that was rewritten most.",
            "The author revised the manuscript nine times — trimming 120 pages, deepening two characters, and rewriting the final chapter completely — before it reached the 380-page version readers loved.",
            "A well-chosen metaphor does in one line what twenty pages of explanation cannot, which is why great writers treat every comparison as a precious resource.",
            "The poet walked the same riverside path for thirty years, and each walk produced a different poem, because the river changed and the walker changed with it.",
            "When asked about inspiration, the famous novelist pointed to her desk: 'It is quite simple. I write, I read, and I wait — usually in that order.'",
        ],
        7: [
            "The memoir, spanning four decades and three continents, opens with a description of sea fog so thick that the child narrator could taste salt in every breath; it closes with the ocean calm and empty, a mirror of a life lived fully.",
            "Editors speak of the 'invisible art' of shaping a book: choosing where chapters break, deciding which comma to cut, and silencing the narrator's own voice so the story can speak for itself.",
            "Between 1950 and 2000, the average length of a best-selling novel grew from 240 to 510 pages; critics argue this reflects not richer storytelling but the industry's preference for books that feel substantial on a shelf.",
            "Translation is the art of losing and finding: the translator surrenders poetry in one language and recovers something adjacent — never identical, always surprising — in another, and the best translations read like original works in both tongues.",
            "The short story demands economy of a kind the novel never asks for; a writer may spend an entire career teaching themselves to say in 3,000 words what they once scattered across 80,000.",
            "In her final lecture, the professor told her students that reading is the only true time machine — an argument that will not appear on the exam, but one she hoped they would carry for the next fifty years.",
        ],
        8: [
            "Scholars of rhetoric trace persuasive writing to five classical canons — invention, arrangement, style, memory, and delivery — and note that the ordering is deliberate: you cannot speak with elegance until you know what you mean to say, and you cannot rewrite until you have written.",
            "The archetypal hero's journey, outlined by Joseph Campbell in 1949, comprises 17 stages, from the call to adventure to the return with the elixir; nearly every major film of the past century, from 'Star Wars' to 'The Matrix,' can be mapped onto its structure, and its persistence suggests storytelling is less an invention than a discovery.",
            "In the 19th century, serialized fiction turned novel reading into a shared weekly event: families gathered on Saturday afternoons to read the next installment of Dickens aloud, subscription numbers exceeding 100,000 for a single story — a reminder that cliffhangers are not a modern invention but a 170-year-old tradition.",
            "Literary critics distinguish between four layers of irony — verbal, dramatic, situational, and cosmic — and argue that mastering the first three unlocks the full depth of Austen, while the fourth explains the bleak humor that pervades Kafka, where characters are consistently trapped by forces larger than comprehension.",
            "The great stylistic revisions of modern prose — from the long periodic sentences of the Victorians to the clipped fragments of Hemingway — can be quantified: average sentence length in American fiction fell from 29 words in 1850 to 14 words in 1990, a shift that mirrored the accelerating tempo of modern life.",
            "Rhetoricians since Aristotle have taught that persuasion rests on three appeals — logos, pathos, and ethos — and that the most durable arguments balance all three; a claim supported only by logic feels cold, one driven only by emotion feels manipulative, and only the fusion of evidence, feeling, and character survives scrutiny.",
        ],
        9: [
            "The essayist William Hazlitt once observed that 'the more we do, the more we can do,' and modern productivity research confirms the old paradox: writers who produce a draft every morning, no matter how rough, report 40% less anxiety about blank pages than those who wait for inspiration — suggesting that momentum, not mood, is the true engine of output.",
            "In the mid-20th century, the 'novel of manners' gave way to the 'novel of consciousness,' a shift scholars attribute to Woolf and Joyce; the difference is measurable in punctuation alone — the average chapter in Joyce's 'Ulysses,' published in 1922, contains 2,300 commas, while a comparable Victorian chapter contains fewer than 900, because interior voices do not pause the way formal sentences do.",
            "Reading speed research reveals a comfortable paradox for book lovers: comprehension peaks near 260 words per minute, yet the most accomplished nonfiction readers average only 300 words per minute — while skimmers, racing past 800 words per minute, retain barely 30% of the argument, proving that the fastest reader is rarely the most reliable one.",
            "The Oulipo group, founded in 1960, constructed entire novels under self-imposed constraints — Georges Perec wrote a 300-page book, 'La Disparition,' in which the letter 'e' never appears — demonstrating that limitation sharpens creativity; critics note that Perec's constraint rarely distracts the reader, and the story reads like an ordinary (if lithe) mystery.",
            "Between 1800 and 1900, the English lexicon absorbed over 20,000 new words, many borrowed wholesale from science — 'cell,' 'virus,' 'oxygen,' and 'evolution' all entered common usage within those decades — because an expanding age of discovery demanded a vocabulary large enough to describe what telescopes and microscopes were revealing to astonished eyes.",
            "Writing instructors often assign the 'imitation exercise': students copy a famous paragraph by hand, then draft an original piece that hews to its cadence; research at three universities found that this practice improved sentence variety scores by 34%, because imitation — long dismissed as lesser craft — is in fact how every great stylist from Milton to Morrison learned to bend language to its limits.",
        ],
        10: [
            "The concept of 'framing' holds that the same facts produce different conclusions depending on the lens applied: a 90% survival rate and a 10% mortality rate describe identical outcomes, yet patients offered the former choose surgery 25% more often — a finding that has reshaped medical consent forms and illustrates why precise language is not merely stylistic but ethical.",
            "At the 1851 Great Exhibition in London, visitors encountered a paradox of literacy: 6 million people — a third of England's population — moved through the Crystal Palace, yet the average working-class attendee could name fewer than 20 of the 100,000 objects displayed; the show made the ease of abundance visible while revealing how rarely seeing translates into knowing.",
            "Etymology traces 'sincere' to the Latin for 'without wax,' referring to the practice of filling cracks in defective marble; the lesson for writers is that the most persuasive voice is the one that openly admits its cracks — transparency converts the reader from skeptic to ally, a principle that modern studies of brand trust, with 81% of consumers valuing honesty over polish, continue to confirm.",
            "The longest sentence in modern literature, a single 823-word construction inside 'Ulysses,' survives as a feat of controlled breath; linguists who analyzed its structure found 14 subordinate clauses wound around a single main clause at its core, and they argue the form mirrors cognition itself — thoughts do not arrive in tidy units but in branching webs that language must somehow hold together.",
            "When the printing press reduced the cost of a book by 90% in the 1450s, it did not merely spread literacy; it created the conditions for a new kind of reading — silent, solitary, and critical — because readers no longer needed an entire community to perform a text aloud, and that shift, historians argue, quietly laid the psychological groundwork for the Reformation and the scientific revolution.",
            "Borges imagined a library containing every possible book; the mathematics are staggering — for a modest vocabulary of 100 characters and sentence length of 80 symbols, the universe of possible texts exceeds the number of atoms in the observable universe by a factor of 10 to the power of the number raised to 7 — yet his deeper point was human: a library of everything is a library of nothing, and meaning emerges only when selection, memory, and a listening reader enter the vast silent stacks.",
        ],
    },
    "Programming": {
        1: [
            "print hello world to start your coding journey today",
            "variables store values that our programs can reuse",
            "if the condition is true then the code will run",
            "a function is a small reusable block of code",
            "save your file before you run the program",
            "loops repeat a task until we tell them to stop",
        ],
        2: [
            "a loop repeats the same block of code until a condition changes",
            "comments explain the code to other developers and to your future self",
            "strings hold text and numbers hold values that we can calculate",
            "when you call a function it returns a value you can store in a variable",
            "indentation matters in many languages because it defines the structure",
            "boolean values are true or false and drive every decision in a program",
        ],
        3: [
            "a stack uses the last in first out rule while a queue uses first in first out",
            "the binary search algorithm finds an item in a sorted list using only a few steps",
            "git tracks every change you make so you can travel back to any earlier version",
            "a dictionary maps keys to values and looks them up very quickly by hashing",
            "testing your code with edge cases prevents bugs from appearing in production",
            "recursion solves a big problem by calling a smaller version of itself repeatedly",
        ],
        4: [
            "the event loop processes tasks one at a time and upgrades long operations to worker threads",
            "a rest api exposes endpoints that clients consume with simple http verbs like get and post",
            "object oriented design groups data and behavior into classes, keeping related logic together",
            "caching frequently accessed results trades a little memory for a large gain in response time",
            "the database index works like a books index, letting queries jump straight to the data",
            "version control, code review, and automated tests form the safety net of professional teams",
        ],
        5: [
            "Quick sort partitions an array around a pivot element and averages only O(n log n) comparisons, making it the default choice in 9 of 10 standard libraries.",
            "The HTTP status code 404 means the resource was not found, while 403 means forbidden and 429 signals you are being rate limited by the server.",
            "A SQL join combines rows from two tables: an inner join returns only matches, while a left outer join keeps every row from the left table regardless of the right.",
            "The JavaScript event loop processes microtasks before macrotasks, which is why this promise logs before that setTimeout even with a zero millisecond delay.",
            "Python's Global Interpreter Lock allows only one thread to execute bytecode at a time, so CPU-bound tasks usually parallelize better with multiple processes than threads.",
            "A hash table achieves O(1) average lookups by mapping keys to array slots through a hash function and resolving collisions with chaining or open addressing.",
        ],
        6: [
            "In document databases like MongoDB, embedding a sub-document is faster for reads within a single request, whereas references and joins make sense when records are updated independently; the trade-off reverses at roughly 16 megabytes of embedded data.",
            "Functional programming treats functions as values: higher-order functions like map and filter operate on collections without mutating state, which eliminates entire classes of bugs that plague imperative code in large codebases.",
            "A race condition occurs when two threads read and write shared memory in an unpredictable order; locks fix it but introduce deadlock risk, so modern code increasingly relies on immutable data structures and atomic primitives instead.",
            "The CAP theorem states that a distributed system can guarantee only two of consistency, availability, and partition tolerance; in practice, most internet scale systems choose availability and partition tolerance, accepting eventual consistency.",
            "Compilers translate high-level source into machine instructions through several passes: tokenizing, parsing into an abstract syntax tree, performing type checking, and finally emitting optimized code that runs in a fraction of the original's execution time.",
            "Regex pattern matching can search text in linear time using automata, yet naive backtracking implementations suffer catastrophic slowdowns; the famous 'catastrophic backtracking' vulnerability froze a major web service for 6 hours in 2020.",
        ],
        7: [
            "The Git object model stores every commit as a directed acyclic graph: each commit references its parents, a tree of file states, and a snapshot of metadata; because history is append-only, rewriting history with rebase demands force-pushing, which 78% of surveyed teams explicitly avoid on shared branches.",
            "Time complexity analysis uses big-O notation to describe growth: a binary search on 1 million sorted items needs only 20 comparisons, while a linear scan might need all 1,000,000; the difference determines whether your function scales to '10,000 or crashes at 10 million.",
            "Row-level versus statement-level triggers behave differently: with a single UPDATE statement touching 500 rows, a statement trigger fires once while a row trigger fires 500 times, which is why production databases often prefer statement-level triggers for auditing and row-level triggers for per-record validation.",
            "Web security follows a simple hierarchy of trust: never trust input. Every endpoint must validate, sanitize, and parameterize — 62% of admitted data breaches in corporate penetration tests began with a single unsanitized search query that found its way into an SQL statement.",
            "Container images layer each instruction: changing one layer near the top is cheap, but changing a layer near the base forces a full rebuild of everything above it, which is why Dockerfiles order dependency installation before source code to keep rebuilds under 15 seconds.",
            "An API rate limiter implemented with a sliding window counter accepts 100 requests per minute while a token bucket allows bursts of up to 30 instantaneous requests — the right choice depends on whether your service favors even load or peak responsiveness for interactive clients.",
        ],
        8: [
            "Database isolation levels form a trade-off ladder: Read Uncommitted allows dirty reads, Read Committed prevents them but allows non-repeatable reads, Repeatable Read fixes row consistency, and Serializable guarantees full equivalence to running transactions one at a time; PostgreSQL's default of Read Committed with MVCC gives snapshot consistency for 99% of real workloads.",
            "A hash join first builds an in-memory hash table from the smaller table (using roughly one byte per row), then streams the larger table probing it once; with tables of 10,000 and 1,000,000 rows, this approach runs in linear time versus the quadratic cost of a naive nested loop join, explaining why SQL engines choose join strategies by analyzing statistics.",
            "Understanding Big-O requires more than memorizing notation: an O(n²) algorithm on 50,000 items performs 2.5 billion operations, taking around 8 seconds on a modern CPU, while a linearithmic sort of the same data runs in under 0.02 seconds — a difference of 400× that engineers feel as real latency the moment customers arrive.",
            "Microservices trade transparency for independence: a 12-service application with 80% inter-service calls executes each user action across an average of 3.4 services with 2 timeouts per 1,000 requests, which is why the pattern demands distributed tracing, circuit breakers, and idempotent retries — complexity paid for by the freedom to deploy each service at its own cadence.",
            "A compiler's optimizer performs constant folding, dead-code elimination, and loop unrolling across hundreds of passes; LLVM's middle end alone contains 82 transformation passes, and the difference is measurable: hand-rolled code compiled unoptimized runs at 40% of the speed of the same source processed with -O2 flags — a 2.5× win bought purely by automated analysis.",
            "The actor model, popularized by Erlang and adopted in modern toolkits, treats each entity as an isolated process that communicates only through immutable messages; when a worker crashes, its supervisor restarts it within milliseconds while clients reconnect transparently; telecom systems built this way have reached 99.9999999% availability, about 3 seconds of downtime per year.",
        ],
        9: [
            "Distributed consensus algorithms like Raft guarantee safety even when a minority of nodes fail: a leader is elected through a randomized timeout, every entry is replicated to a majority before commit, and log integrity is checked by term numbers — properties that make 5-node clusters tolerate up to 2 simultaneous failures without losing a single acknowledged write.",
            "Writing-efficient code begins with measuring: a profiler revealed that 71% of execution time in a typical web request is spent in 4 database queries, so indexing two columns and adding one JOIN cut the response from 2,800 to 380 milliseconds — a 7.4× improvement realized without abandoning the architecture or rewriting the language.",
            "The Turing machine, though it has hypothetical infinite tape, is the accepted definition of computation: a language is computable if a Turing machine can decide it, undecidable if not, and the halting problem is famously undecidable — results that place hard mathematical limits on what any programming language, at any CPU speed, can ever accomplish.",
            "Two-phase commit guarantees atomic distributed transactions but blocks on coordinator failure; the saga pattern avoids blocking by dividing the operation into steps with compensating actions, accepting that an order might be confirmed before payment completes — a trade of strict atomicity for availability that exactly matches the needs of payment orbits processing 1,200 transactions per second.",
            "Every serious engineer understands cache locality: a 64-byte cache line means accessing element 0 and element 63 of an array is one memory fetch, while striding every 4,096 bytes evicts the line each time; processing a matrix row-by-row instead of column-by-column lit up a 6× speedup purely by honoring the hardware's assumptions about how memory is read.",
            "Formal verification replaces probabilistic testing with proof: the seL4 microkernel was verified in 10,900 proof obligations, proving the absence of buffer overflows, NULL dereferences, and memory leaks across 9,500 lines of C; its developers report that verification cost 20 engineering-years but eliminated an entire class of remote-code-execution vulnerabilities that no amount of black-box testing could have guaranteed against.",
        ],
        10: [
            "Zero-knowledge proofs let one party convince another that a statement is true without revealing why: deploying a 256-bit proof of a computation on Ethereum cost 240,000 gas in 2024 versus 8 million for re-execution — a 33× saving — while proving libraries moved verification time down from minutes to under 2 seconds, a trajectory that crypto engineers expect to make privacy-preserving transactions economically dominant.",
            "The CAP theorem, formalized by Eric Brewer in 2000, states that in the presence of network partitions a distributed system must sacrifice either consistency or availability; DynamoDB-family systems choose availability, keeping stale reads for at most 10 seconds under partition, whereas Spanner chooses linearizability by exchanging wall-clock synchronization across atomic clocks — two legitimate answers to the same fundamental law.",
            "When garbage-collected language runtimes meet real-time requirements, engineers reach for escape hatches: Go's hybrid GC pauses for an average of 1.5 milliseconds at 2 gigabytes of live heap by using a concurrent algorithm that clears the stack and heap barriers, while Rust sidesteps the entire problem by enforcing ownership at compile time — zero runtime collector, zero pause, but a borrow checker learning curve of roughly 6 months.",
            "The epic generation of 2023 demonstrated a cruder but potent form of optimization: training a 175-billion-parameter language model consumed 3.4 gigawatt-hours of electricity, yet model quantization reduced the inference cost 8-fold by representing weights as 4-bit integers; the insight that 90% of neural-network value survives 16× compression has since driven a generation of efficient deployments on devices drawing under 5 watts.",
            "Provably secure cryptographic systems rest on problems believed hard rather than problems proven impossible: RSA survives on the practical infeasibility of factoring 2,048-bit composites, currently estimated to require an exaflop-years of work, while Post-Quantum standardization (led by NIST's 2024 selections) readies lattice-based signatures like Dilithium that resist even hypothetical quantum computers capable of running Shor's algorithm at scale.",
            "The engineer's oldest lesson is the closest loop: in a 2024 latency study across 40 production services, reducing a single hot-path round trip from a remote cache to an in-process map cut p99 latency from 210 milliseconds to 31 milliseconds — a 6.8× improvement — because the 9 microseconds of in-memory access removed the 180 milliseconds of network, serialization, and scheduling that no amount of server-side tuning could have recovered afterward.",
        ],
    },
    "Science": {
        1: [
            "water freezes into ice when it gets very cold outside",
            "plants need sunlight water and air to grow healthy",
            "the moon travels around the earth in twenty eight days",
            "magnetic force pulls metal objects toward a magnet",
            "green leaves use light to make food for the plant",
            "a shadow appears when light is blocked by an object",
        ],
        2: [
            "gravity pulls everything toward the center of the earth with a steady force",
            "the water cycle moves water from clouds to rain and back again through evaporation",
            "animals that eat only plants are called herbivores while meat eaters are carnivores",
            "sound travels through air as waves that our ears turn into what we hear",
            "the human skeleton has about two hundred six bones holding our body together",
            "a battery produces electricity through a chemical reaction that pushes electrons",
        ],
        3: [
            "photosynthesis converts sunlight, water, and carbon dioxide into glucose and oxygen, feeding most of life on earth",
            "the digestive system breaks down food into nutrients that the bloodstream carries to every cell in the body",
            "planets orbit the sun in nearly circular paths, held in place by the balance of gravity and motion",
            "friction between surfaces converts motion into heat, which is why rubbing your hands together warms them up",
            "a habitat is the natural home of a species, providing the food, shelter, and climate the organism needs to survive",
            "energy cannot be created or destroyed, only transformed, which is the first law of thermodynamics",
        ],
        4: [
            "the respiratory and circulatory systems work together so that oxygen added in the lungs reaches each cell while carbon dioxide returns",
            "volcanoes form where tectonic plates pull apart or collide, and their eruptions release magma, ash, and gases from deep below",
            "a chemical reaction rearranges atoms into new substances, and the law of conservation of mass guarantees atoms are never lost",
            "the electromagnetic spectrum spans from long radio waves to short gamma rays, and visible light occupies just one narrow band",
            "natural selection favors traits that improve survival, so populations change gradually across many generations",
            "a solution is a mixture of a solute dissolved in a solvent, and concentration measures how much solute is present",
        ],
        5: [
            "The speed of light is 299,792,458 meters per second, fast enough to circle the Earth 7.5 times in a single second, yet even this speed takes 8.3 minutes to reach us from the sun.",
            "A neuron transmits signals electrically through its axon at up to 120 meters per second, while communication between neurons relies on chemicals called neurotransmitters across the tiny synaptic gap.",
            "pH is measured on a scale from 0 to 14: lemon juice sits near pH 2, pure water is neutral at pH 7, and soap reaches about 10; each unit represents a tenfold change in acidity.",
            "The human body contains about 37 trillion cells, and every one of them is replaced over time; your red blood cells live only 120 days, so about 2.4 million are produced fresh every second.",
            "Earth's atmosphere extends about 480 kilometers before fading into space, yet 99% of its mass lies within 32 kilometers of the surface, where weather, breathing, and flight all occur.",
            "An earthquake's magnitude follows a logarithmic scale: a magnitude 6 event releases about 32 times the energy of a magnitude 5 event, so comparing them is like comparing camping sparks to a bonfire.",
        ],
        6: [
            "The Hubble Space Telescope has observed galaxies 13.4 billion light-years away, meaning their light left them only 400 million years after the big bang; because light has a finite speed, telescopes are literally time machines.",
            "Darwin's finches on the Galapagos Islands evolved 13 distinct beak shapes from a single ancestor in roughly 1 million years, each adapted to a different seed, insect, or cactus, offering a living classroom of natural selection.",
            "A single gram of soil contains up to 10 billion bacteria across thousands of species; these microbes recycle nutrients, fix nitrogen, and support plants, making soil one of the most biodiverse habitats on the planet.",
            "Atomic clocks measure vibrations of cesium atoms at exactly 9,192,631,770 cycles per second, enabling global positioning accuracy of 4 meters; a roadside 10-meter error across a month would arise from losing just 10 microseconds per day.",
            "Open-heart surgery requires cooling the body by roughly 12 degrees, slowing metabolism so the brain tolerates minutes without blood flow; during the procedure, a machine called a heart-lung bypass substitutes for both organs.",
            "Coral reefs cover less than 0.1% of the ocean floor yet host about 25% of all marine species, thousands of fish and invertebrate species depending on them for shelter, food, and breeding grounds.",
        ],
        7: [
            "The greenhouse effect raises Earth's average temperature by about 33 degrees Celsius: without atmospheric carbon dioxide, water vapor, and methane, the planet would average around minus 18 degrees instead of its current 15 degrees, an object lesson in how thin the habitable envelope really is.",
            "Enzymes accelerate biochemical reactions by factors of a million or more: catalase converts hydrogen peroxide to water and oxygen so quickly that a single molecule can process 40 million substrate molecules per second, and every living cell relies on thousands of such catalysts working in parallel.",
            "The periodic table arranges 118 known elements by increasing atomic number, and elements in the same group share chemical properties; the 118th element, oganesson, was first synthesised in 2002 and exists for only about 0.7 milliseconds before decaying.",
            "Plate tectonics explains how continents drift at roughly the speed fingernails grow (about 5 centimeters per year), yet over 200 million years that slow crawl tore apart Pangea, shaped ocean basins, and drove the earthquakes and volcanoes we observe along today's zone boundaries.",
            "The Doppler effect stretches light from receding galaxies toward redder wavelengths; Edwin Hubble's 1929 measurements — over 46 galaxies — of this red shift revealed the universe's expansion at about 70 kilometers per second per megaparsec.",
            "Circadian rhythms keep our internal clocks on a 24-hour cycle: exposure to morning light suppresses melatonin and shifts body temperature, while a single week of late-night screen use can delay sleep onset by up to 40 minutes through blue-light suppression of the sleep hormone.",
        ],
        8: [
            "Radioactive decay follows exponential mathematics: a carbon-14 atom in a fossil decays with a half-life of 5,730 years, so after 57,300 years only 1/1000 of the original remains — precisely the measurement window (about 50,000 years) that makes radiocarbon dating the backbone of archaeology for objects from the Stone Age onward.",
            "The human genome contains about 3.1 billion base pairs, and the mutations that power evolution occur at a rate of roughly 1 per 100 million bases per generation; the Human Genome Project, completed in 2003 at a cost of $2.7 billion, decoded all of it, and a full sequence now costs under $1,000.",
            "Thermodynamics governs why ice melts: at 0 degrees Celsius, the addition of 334 kilojoules per kilogram breaks the hydrogen bonds holding ice crystals together without raising the temperature; the same physics describes how a snowball packed tightly resists melting longer, because squeezing removes the insulating air gaps.",
            "The food chain transfers only about 10% of energy between each link: a field producing 10,000 calories of plant matter supports only 1,000 calories of herbivores and 100 calories of predators — the foundation of why diets high on the food chain require vastly more land, water, and energy per calorie eaten.",
            "Neurons communicate by managing ion gradients across their membranes; a typical neuron rests at about -70 millivolts yet can fire action potentials at up to 400 times per second, and the brain's combined 86 billion neurons each connect to roughly 7,000 others, yielding a synaptic network whose total connections exceed the number of stars in the Milky Way.",
        ],
        9: [
            "The structure of DNA was solved in 1953 from a diffraction photograph showing an 'X' pattern that revealed a double helix of 2-nanometer width; Watson and Crick's paper spanned barely 900 words, yet the discovery won the Nobel Prize in 11 years and launched a biology that now sequences a human genome for the price of a pair of running shoes.",
            "Quantum mechanics defies intuition at scales below the micrometer: an electron is both a particle and a wave, and Heisenberg's uncertainty principle sets a fundamental limit — you cannot know both the position and momentum of a particle beyond Planck's constant divided by the measurement uncertainty, a bound no experiment, however precise, can ever pierce.",
            "The Earth's interior is read by seismology: P-waves travel fastest at 8 kilometers per second through the mantle, while S-waves, which cannot pass through liquids, vanish at 2,900 kilometers depth, proving the outer core is molten iron; these same waves, measured across 100 stations, localize an earthquake's epicenter from three arrival-time differences.",
            "In the 1980s, two teams racing to solve HIV's replication cycle discovered reverse transcriptase, an enzyme that copies RNA into DNA, overturning the 'central dogma' of biology that information flows only from DNA to RNA to protein; that discovery led directly to antiretroviral drugs that reduced AIDS deaths by 69% within a decade.",
            "Climate models couple 5 sub-routines — atmosphere, ocean, ice, land, and biosphere — exchanging 200,000 data points per time step; the most recent generation, run on exascale machines, reproduces observed warming since 1850 within 0.3 degrees Celsius, giving confidence that projections of 2 to 4 degrees of surface warming by 2100 reflect physics, not speculation.",
            "A star's life is dictated by its mass: a star like the sun will burn hydrogen for 10 billion years, expand into a red giant, and leave a dense white dwarf, while a star with 20 times the sun's mass fuses heavier elements up to iron, then collapses and explodes as a supernova, forging in seconds every element heavier than iron, including the calcium and iron in human bones.",
        ],
        10: [
            "The double-slit experiment, repeated in 2024 at 1,024 detectors, demonstrates the deepest puzzle in physics: single photons fired one at a time still form interference fringes, yet instrumenting the slits to learn which path each photon takes collapses the pattern instantly — degree of decoherence, not human observation, determines whether matter behaves as wave or particle.",
            "The Cambrian explosion, compressed into 20 million years some 540 million years ago, produced the broad diversity of animal body plans: nearly all 35 living phyla first appear in the fossil record of that window, and paleontologists now attribute the suddenness not to a single cause but to a rare convergence of oxygen rising above 20% of the atmosphere, the evolution of predation, and the appearance of skeletons.",
            "General relativity predicts that GPS clocks, orbiting at 20,200 kilometers where gravity is weaker, run 38 microseconds faster per day than terrestrial clocks; without relativistic correction, satellite navigation would drift about 10 kilometers each day — a practical daily dependence on Einstein's 1915 equations at the heart of every modern navigation system on Earth.",
            "The microbiome forms an ecosystem of roughly 100 trillion microbial cells competing and cooperating within the gut; researchers who analyzed 6,000 samples found that diversity — not count — predicts health, and that diet shifts can alter measurable community structure within 24 hours, turning nutrition science into a field where sequencing replaces guesswork.",
            "Where matter and antimatter should have annihilated at the big bang, a slight asymmetry left about 1 extra particle per billion — that residue became every atom in every star, planet, and organism; experiments at CERN measure this CP-violation through decays of neutral kaons at a rate of about 2 in 1,000, a tiny, measurable crack in symmetry that explains why anything exists at all.",
            "The observable universe contains an estimated 200 billion galaxies averaging 100 billion stars each; light from the most distant ever photographed has been traveling for 13.5 billion years at 299,792 kilometers per second — over the course of which the universe expanded by a factor of roughly 1,340, meaning the photons traveled 370 billion light-years of comoving distance to reach a telescope designed, funded, and operated by creatures that did not exist when they departed.",
        ],
    },
    "Mathematics": {
        1: [
            "two plus three equals five and six minus four equals two",
            "a square has four equal sides and four right corners",
            "count the apples and write down the total number",
            "one half is bigger than one third but smaller than one",
            "seven multiplied by two gives us the number fourteen",
            "a triangle has three sides and three corners altogether",
        ],
        2: [
            "the perimeter of a rectangle is two times its length plus two times its width",
            "even numbers end in zero two four six or eight while odd numbers do not",
            "fractions compare parts of a whole like a half of an apple pie",
            "the commutative property says that adding in any order gives the same sum",
            "a dozen equals twelve and a century equals one hundred years",
            "place value tells us that in the number 352 the five means fifty",
        ],
        3: [
            "an equation states that two expressions are equal, and solving it means finding the unknown value",
            "the area of a rectangle is base times height, and its perimeter is simply double the sum of its sides",
            "prime numbers have exactly two factors, one and themselves, so 2, 3, 5, 7, and 11 are all primes",
            "a percentage is a fraction out of one hundred, so 25 percent is the same as one quarter",
            "the distributive property lets us rewrite a times brackets b plus c as a b plus a c",
            "a sequence is a list of numbers following a rule, like adding three each time",
        ],
        4: [
            "the pythagorean theorem links the sides of a right triangle: the square of the hypotenuse equals the sum of the squares of the other two sides",
            "a negative number times a negative number gives a positive product, which surprises many students at first",
            "the mean of a data set is its average, the median is the middle value, and the mode is the most frequent one",
            "an angle is measured in degrees, a right angle is exactly ninety, and a straight angle reaches one hundred eighty",
            "exponent notation shows repeated multiplication, so three to the fourth equals three times three times three times three",
            "probability measures how likely an event is, from zero for impossible up to one for certain",
        ],
        5: [
            "The quadratic formula, x equals negative b plus or minus the square root of b squared minus 4ac all over 2a, solves any quadratic equation regardless of whether it factors cleanly.",
            "The volume of a cylinder is pi times the radius squared times the height, so a cylinder with radius 4 and height 10 holds about 502.7 cubic units.",
            "The Fibonacci sequence begins 1, 1, 2, 3, 5, 8, 13 — each term the sum of the two before — and it appears in sunflowers, pinecones, and seashell spirals, where ratios of consecutive terms approach the golden ratio 1.618.",
            "A function maps each input to exactly one output; the vertical line test confirms a graph is a function when no vertical line crosses it more than once.",
            "The probability of rolling a sum of 7 with two dice is 6 out of 36, about 16.7 percent, because six of the 36 possible combinations produce that total.",
            "The slope of a line measures its steepness as the change in y divided by the change in x, so slope equals rise over run for any two points on the line.",
        ],
        6: [
            "Graph theory, largely founded by Euler in 1736, models connections as vertices and edges; the famous Königsberg bridge problem was impossible because four landmasses had an odd number of bridges, a parity argument that birthed an entire branch of mathematics.",
            "The number pi is irrational, meaning its decimal expansion never terminates or repeats; the current record computation reached 100 trillion digits in 2022, yet just 39 digits of pi suffice to compute the circumference of the known universe to within the width of a hydrogen atom.",
            "Statistics divides into descriptive methods, which summarize data like mean and standard deviation, and inferential methods, which draw conclusions about populations from samples; a sample of 400 randomly chosen students can estimate a school's opinion within about 5 percentage points.",
            "Exponential growth doubles quantities at a fixed rate: an investment earning 7 percent annually takes roughly 10 years to double by the rule of 72, while a single bacterium dividing every 20 minutes would exceed 10 million in a single day.",
            "Matrix multiplication is not commutative: rotating then translating differs from translating then rotating, and this ordered structure powers computer graphics where a 3D object is transformed by composing 4 by 4 matrix operations into a single view matrix.",
            "The pigeonhole principle, deceptively simple, states that if n items are placed into fewer than n containers, at least one container holds two items; it proves that among any 13 people, two share a birth month, and among any 367, two share a birthday.",
        ],
        7: [
            "The Fundamental Theorem of Calculus connects integration and differentiation as inverse operations: the definite integral of a function equals the difference in its antiderivative evaluated at the limits, transforming areas, which are hard, into evaluations, which are routine — a bridge that unlocked physics, engineering, and probability.",
            "Set theory underlies all of mathematics: a set with n distinct elements has exactly 2 to the power of n subsets, so a set of 6 elements produces 64 distinct subsets, which explains why a 6-bit binary word can represent 64 different symbols — the link between abstract collections and the byte's 256 states.",
            "Geometry's parallel postulate resisted proof for 2,000 years until non-Euclidean geometry revealed that through a point not on a line, either zero or infinitely many parallels may exist; those 'impossible' geometries turned out to describe curved spacetime and are now indispensable in GPS satellite correction.",
            "Modular arithmetic, or clock arithmetic, wraps numbers around a fixed modulus: a clock at 23:00 plus 5 hours reads 04:00, because 28 mod 24 is 4; this same arithmetic powers computer checksums, ISBN validation, and the RSA encryption that keeps web transactions secure.",
            "A permutation arranges items in a specific order, while a combination ignores order; the number of ways to choose 3 players from a team of 8 is 56 combinations, but arranging those same 3 in positions yields 336 permutations — counting problems whose difference decides lottery odds and championship draws alike.",
            "In any right triangle with legs a and b and hypotenuse c, the Pythagorean triple 5, 12, 13 holds exactly as 25 plus 144 equals 169; more than 300 distinct proofs of the theorem exist, including one by a 12-year-old student, and thousands of triples satisfy the same equation today.",
        ],
        8: [
            "The birthday problem surprises every class it visits: with just 23 people in a room, the probability that two share a birthday exceeds 50 percent, and with 70 people it exceeds 99.9 percent — a counterintuitive result that follows from computing not the chance of a match but the complement, the rapidly shrinking probability of all birthdays being distinct.",
            "A parabola takes the form y equals ax squared plus bx plus c, and its vertex marks the maximum or minimum; the reflection property of parabolas is exploited in satellite dishes and car headlights, where rays from the focus reflect parallel — pure geometry engineered into everyday hardware.",
            "The standard normal distribution, shaped like a bell with mean 0 and deviation 1, places 68.27 percent of data within one standard deviation and 99.73 percent within three; this universal shape lets statisticians compare any measurement across scales, from exam scores to blood pressure, using the same z-score tables.",
            "Proof by induction verifies infinite claims in two steps: show the base case holds, then assume it holds for n and prove it for n plus 1; the method demonstrates, for example, that the sum of the first n integers equals n times n plus 1 over 2, valid for every positive integer in existence.",
            "The ancient Egyptians approximated pi as 3.16 and the Babylonians as 3.125, while Archimedes pinned it between 223/71 and 22/7 using 96-sided polygons; although each estimate is within 1 percent of the true value, human craving for precision pushed the computation to 2 million decimals by 1987 using little more than fast multiplication algorithms.",
            "Euler's formula, e to the power of i times pi plus 1 equals 0, unites the five most important constants in mathematics: e, i, pi, 1, and 0, in a single equation; Richard Feynman called it 'the most remarkable formula in mathematics' because it distilled complex analysis, trigonometry, and exponentiation into a relationship that neither intuition nor any single field predicted.",
        ],
        9: [
            "The number 3.14159 ratio between a circle's circumference and diameter has resisted full resolution: 22/7 differs from pi by only 0.04 percent, yet pi's transcendence (proved in 1882 by Lindemann) means its exact value can never be expressed by solving a polynomial equation — settling the ancient problem of squaring the circle, which is impossible, in a single stroke.",
            "A geometric series sums terms that shrink by a constant ratio: 1 plus 1/2 plus 1/4 plus 1/8 forever totals exactly 2, because each partial sum approaches 2 while never quite reaching it; Zeno's paradox of the hare and tortoise rests on precisely this infinite but finite convergence.",
            "Linear equations model proportionality: a straight line through two points has one unique slope, and two lines intersect in one point unless they are parallel; a system of 100,000 linear equations describing a bridge's stresses is solved not graphically but by Gaussian elimination, which performs about n cubed over 3 operations — roughly 3.3 trillion for the full structure — in under 30 seconds on modern hardware.",
            "The Central Limit Theorem, called the workhorse of statistics, states that averages of many independent observations approximate a normal distribution regardless of the original distribution; it justifies polling with 1,500 respondents to a 3 percent margin, and it explains why heights, test scores, and measurement errors all cluster in the familiar bell curve.",
            "Infinity comes in different sizes: the integers are countably infinite and can be listed, while the real numbers are uncountably infinite, proven by Cantor's diagonal argument, which crafts a new number differing from every number on any proposed list; the discovery that infinities are not all equal shocked 19th-century mathematicians and reshaped the foundations of analysis.",
            "Optimization problems ask for the best value under constraints: a farmer with 400 meters of fencing maximizes field area by choosing a square of 100 by 100, and calculus confirms any rectangle deviating from that square loses area; the marginal-analysis method that solves the farm problem is the same one companies use to price products and airlines use to price seats.",
        ],
        10: [
            "The Basel problem stumped mathematicians for 90 years until Euler, in 1735, proved that the infinite sum of reciprocals of squares converges to pi squared over 6 — approximately 1.6449 — connecting the discrete world of integers to the transcendental constant pi in a result so surprising that Euler's contemporaries risked their reputations to verify it by hand.",
            "The 17th-century search to prove that every number that can be written is the sum of at most two primes, known as Goldbach's conjecture, remains unproven after 300 years; computation has verified the claim for every even number up to 4 times 10 to the power of 18, and its persistence illustrates how deceptively simple statements can outlast complex theorems in mathematics.",
            "Calculus measures instantaneous change: the derivative of distance with respect to time is velocity, and of velocity is acceleration; the Fundamental Theorem guarantees that integrating velocity over a trip returns the net displacement, which is precisely how your phone's accelerometer, sampling 100 times per second, reconstructs your walking path.",
            "The arithmetic-geometric mean iteration pioneered by Gauss averages each pair of terms recursively: starting from 1 and 2, successive avs quickly converge, and Gauss discovered that the number of iterations equals log log of the reciprocal of the error; the same iteration underlies modern elliptic-curve cryptography, where the group's structure replaces multiplication with a much harder-to-reverse operation.",
            "Randomness in mathematics turns out to be measurable: a fair coin flipped 1,000 times produces a run of 10 identical flips with probability about 63 percent, and the normal distribution predicts that values beyond 3 standard deviations occur roughly 3 times per 1,000 observations — the precise probabilities that make casino odds, insurance premiums, and clinical-trial cutoffs all computable, rational quantities.",
            "The monster group, the largest sporadic simple group, contains 808,017,424,794,512,875,886,459,904,961,710,757,005,754,368,000,000,000 elements — more than 10 to the power of 53 — yet a finite symmetry structure this enormous fits in a single line of group theory; its discovery united string theory, modular forms, and pure algebra through the mysterious moonshine conjecture, still only partially understood.",
        ],
    },
    "Academic": {
        1: [
            "study a little every day instead of the night before",
            "write your homework in the planner so you never forget",
            "ask the teacher when you do not understand a lesson",
            "keep your desk clean and your notes organized",
            "read the questions twice before you answer them",
            "sleep well the night before your big test",
        ],
        2: [
            "a study plan breaks big goals into smaller daily tasks that feel easy to start",
            "taking careful notes during class helps you review important ideas later",
            "reading a chapter twice, once for ideas and once for details, improves understanding",
            "forming a study group lets you explain concepts and hear how others think",
            "reviewing your mistakes on a quiz is the fastest way to learn the topic",
            "short focused sessions with breaks beat long hours of distracted study",
        ],
        3: [
            "research projects work best when you start with a clear question and plan your time backward from the deadline",
            "an essay needs an introduction that tells the reader the claim, then body paragraphs that support it with evidence",
            "active recall, testing yourself instead of rereading, is among the most powerful ways to retain information",
            "the pomodoro technique splits work into twenty five minute blocks separated by short breaks to protect your focus",
            "paraphrasing a source in your own words proves understanding, while copying text word for word is always wrong",
            "vocabulary grows fastest through reading widely and using new words in your own sentences immediately",
        ],
        4: [
            "the best exam revision is spaced out over weeks, because each review strengthens memory, and last minute cramming creates only fragile recall",
            "when you write citations, the original author gets credit, your argument gains credibility, and plagiarism is avoided entirely",
            "a good thesis statement is specific enough to guide your paper but open enough to argue; vague claims lead to vague essays",
            "asking focused questions during lectures, such as why or what if, turns passive listening into active learning",
            "the reading comprehension strategy of summarizing each paragraph in one sentence builds a map of the whole chapter",
            "digital distraction is best managed by environment: put your phone in another room during deep work sessions",
        ],
        5: [
            "Bloom's taxonomy ranks thinking from remembering to creating: higher-order tasks like evaluating and designing correlate with deeper learning, which is why asking 'what evidence supports this?' beats 'what did the text say?'",
            "The Pomodoro technique prescribes 25 minutes of concentration followed by a 5-minute break; four rounds earn a longer rest, and adherents report a 40% reduction in procrastination within two weeks of daily use.",
            "A research paper argues a claim, supports it with 5 to 8 credible sources, and acknowledges counterarguments; a literature review, by contrast, surveys what is already known and identifies the gap your study will fill.",
            "Annotating while you read — underlining claims, writing questions in margins, and summarizing paragraphs — increases retention by 23% because the active effort of marking forces your brain to evaluate each idea as it arrives.",
            "The Cornell note-taking method splits a page into a cue column, a notes column, and a summary strip, turning a single lecture into both a record and a self-testing tool within one clean structure.",
            "Self-testing, or retrieval practice, outperforms rereading by a large margin: students who quizzed themselves retained 61% of material after a week, versus 34% for students who simply reread their notes.",
        ],
        6: [
            "The Feynman technique builds understanding by explaining a concept in plain language as if to a child: wherever the explanation stumbles, a genuine gap in understanding exists, and re-studying precisely that spot produces durable, exam-ready mastery.",
            "Intelligent tutoring systems, including modern AI assistants, excel at spacing practice: they track each concept's error history and schedule review at the edge of forgetting, a personalization that raises average mastery rates by 18% compared with one-size-fits-all revision plans.",
            "Academic integrity demands proper attribution in every submission; the standard citation formats — APA for social sciences, MLA for humanities, and IEEE for engineering — each specify how quoting, paraphrasing, and referencing sources should be formatted across thousands of possible source types.",
            "A strong lab report follows a fixed arc: an objective states what was measured, the method is described so another scientist could reproduce it, results are presented as tables and figures, and the discussion interprets what the numbers mean in light of the objective.",
            "Cognitive load theory explains why worked examples beat problem solving for beginners: watching a solved problem builds the pattern library a novice lacks, so textbooks wisely alternate example, practice, example, rather than dumping problems before the skill exists.",
            "Time-blocking reserves fixed calendar slots for shallow work, email, and admin tasks while protecting long blocks for deep work; students who block 90-minute focus sessions report spending 2.4 hours more per week on meaningful study simply because structure converts intention into schedule.",
        ],
        7: [
            "The spacing effect, documented since Ebbinghaus's 1885 forgetting-curve experiments, shows that distribution beats massing: a student who studies vocabulary for 20 minutes across 8 days remembers 74% more after a month than one who studies 160 minutes in a single day, a finding replicated across 200 subsequent studies.",
            "Argument mapping, borrowed from formal logic, requires writers to draw their claims, premises, and rebuttals as connected nodes before drafting; instructors who used it in their writing courses observed a 31% improvement in structure scores, because an argument that is invisible in prose becomes visible on paper.",
            "When evaluating sources, the CRAAP test — Currency, Relevance, Authority, Accuracy, and Purpose — provides a five-question checklist; applying it rejects roughly one source in three, a filter that separates a research paper built on scholarship from one built on search-engine convenience.",
            "The dual-coding theory holds that memory forms stronger traces when information appears as both words and images, which is why concept maps pairing labels with diagrams outperform outline notes; students who mapped their chapter readings recalled 27% more key terms at the end of the semester.",
            "The research question is the engine of any study: a focused question frames the scope, dictates the method, and determines what 'good data' looks like, so experienced supervisors spend a full session interrogating the question before they will discuss sources or statistics.",
            "Metacognition — thinking about your own thinking — separates strong from weak learners: high performers estimate their exam readiness within 7% of their actual scores, while poor performers overestimate by 24%, a calibration gap that deliberate self-testing steadily closes.",
        ],
        8: [
            "The European education system's 'flipped classroom' model assigns video lectures as homework and moves problem-solving into class time; meta-analyses across 350 experiments found average exam gains of 12 percentage points, but only when in-class activities actually required the pre-watched material — a finding about follow-through, not film production.",
            "Peer review, standard in academic publishing since the 17th century's Philosophical Transactions, screens roughly 2.3 million papers yearly: editors relay 2 anonymized referee reports, rejecting an average of 62% of submissions, yet studies admit the system occasionally rejects breakthrough work, including the original discovery of the double-helix structure.",
            "The SQ3R method — Survey, Question, Read, Recite, Review — turns a textbook chapter into a deliberate sequence: skimming headings forms a map, converting each heading into a question focuses reading, reciting answers aloud tests recall, and reviewing completes the arc; students trained in SQ3R averaged 26% higher comprehension scores on standardized passages.",
            "Choosing the right statistical test is an academic skill in itself: compare two group means, and a t-test applies; compare three or more, and an ANOVA controls the familywise error; measure association, and correlation or regression fits — and choosing wrong by one step invalidates 19% of the statistics in checked undergraduate research projects.",
            "An annotated bibliography is 3 parts analysis, 1 part summary: each entry summarizes the source in one paragraph, evaluates its authority and relevance in another, and explains its use in the upcoming paper in a third; the process early drafts the literature review and a third of the final essay before writing even begins.",
            "The Interleaving effect emerged from 7 experiments at U.C.L.A.: students who practiced 3 related problem types mixed together outperformed those who drilled one type to exhaustion, scoring 43% higher on a delayed test, because mixing forced them to notice features rather than repeat procedures — practice at choosing matters more than practice at executing.",
        ],
        9: [
            "The 2011 meta-analysis of 225 retrieval-practice studies concluded that taking practice tests raises retention by 20% on average versus restudy; importantly, the benefit persists when tests generate errors, because attempting and failing builds the neural trace needed for later encoding — meaning the best use of a practice test is where you do worst on it.",
            "Academic writing prizes the passive critique that the active voice hides: 'data were collected' foregrounds the evidence while 'I collected data' foregrounds the researcher, and scientific journals have long preferred the former for methodology — though modern style guides from Nature onward now encourage the active voice for clarity where the researcher's choice genuinely mattered.",
            "Project-based learning, championed by 12 national curricula, replaces chapter tests with open-ended artifacts like working water filters or published magazines; the strongest studies show identical exam performance but 21% higher motivation and 33% better collaboration scores, evidence that skills of the process — not just scores of the product — are the real curriculum.",
            "The multi-tasking myth persists despite 40 years of evidence: switching between tasks costs up to 40% of productive time in attention residue, and even brief interruptions of 2.8 seconds double the error rate on a primary task — findings that make single-tasking not a preference but the empirically fastest way to study.",
            "Rubric-based grading evolved from 1980s assessment science: a well-built rubric describes performance at 3 to 5 levels across dimensions like argument, evidence, and mechanics; meta-analyses find rubrics improve grading reliability by 0.7 standard deviations and, more striking, raise student achievement because learners finally see the exact criteria their grade measures.",
            "The 2006 study of 580 freshmen found that students taught with tangible models, moving manipulatives, and whiteboard sketching outperformed peers taught with formulas alone — on equations, poor students posted closing achievement gaps of 25 percentage points by semester's end; the lesson: mastery of representation, not memorization, is the transferable skill.",
        ],
        10: [
            "The 40-hour scholarship in deliberate practice has one consistent headline: ten thousand hours is a misreading — the real variable is quality, not quantity; studies of chess masters and musicians show that 4 hours of daily focused effort, with immediate feedback and constant difficulty adjustment, builds expertise 2.6 times faster than the same clock time spent in unfocused rehearsal.",
            "Around 2010, learning scientists unified decades of experiments into a single model: learning is the expansion of working memory into automated long-term structures; on this model, the best pedagogy provides worked examples first (low load), then faded scaffolding (moderate load), then independence — a sequence that raises transfer-test scores by 0.8 standard deviations across 6 controlled trials.",
            "The intellectual-honesty clause in academic codes extends well beyond plagiarism: fabricating data, coaching a peer during an exam, using unauthorized software, or reusing one's own submitted work without disclosure all constitute misconduct; universities worldwide reported 21,400 such cases in 2024, and 1 in 3 involved submissions that a plagiarism detector alone could never have caught.",
            "Dialectical reading, the practice of arguing with a text before accepting it, separates advanced scholars from diligent students: the reader first reconstructs the author's argument generously, then attacks its weakest premise with contrary examples, then synthesizes the strongest surviving position; academics trained in this method review 38% more accurately in blind quality checks of their written critiques.",
            "The admissions-essay literature converges on a single reliable predictor of success: specificity. Essays that name five concrete episodes (a collapsed prototype, a ruined bake sale, a failed interview) and connect each to a growing skill receive 2.1 times higher evaluator ratings than essays of equal quality written in generalities — because evaluators, human or algorithm, search for evidence of self-awareness rather than declarations of it.",
            "When the Ancient library of Alexandria compiled its collections, the editors crossed-reference every scroll with its teachers, students, and prior disputations, creating a system that modern knowledge-management software still imitates; the practice survives because connecting a fact to its history, its orator, and its critics — metadata layered on text — is the same act that turns a memorized benchmark into a contested, understood, and wieldable idea.",
        ],
    },
    "Interview": {
        1: [
            "tell me a little bit about yourself and your hobbies",
            "why do you want to work for this company",
            "what are your strengths and what are your weaknesses",
            "where do you see yourself in five years from now",
            "why should we hire you instead of the other candidates",
            "tell me about a time you worked well within a team",
        ],
        2: [
            "describe a time when you solved a difficult problem while working under pressure",
            "how do you prioritize your tasks when everything seems urgent at the same time",
            "tell me about a mistake you made at work and what you learned from it",
            "what skills do you bring to this role that other candidates may not have",
            "how do you handle feedback that you disagree with from a colleague or manager",
            "describe your ideal work environment and the culture you thrive within",
        ],
        3: [
            "tell me about a project you led from start to finish, including how you managed setbacks along the way",
            "how do you stay organized when managing multiple deadlines with competing priorities",
            "describe a time you had to explain a technical or complex idea to a non-expert audience",
            "what motivates you to come to work every day, and how does that drive your performance",
            "give me an example of a time you turned a conflict with a coworker into a productive outcome",
            "how do you approach learning a completely new skill or technology on a tight schedule",
        ],
        4: [
            "tell me about a measurable achievement you delivered; include the numbers that prove the impact",
            "how do you decide when to ask for help versus when to solve a problem independently",
            "describe a situation where you had to break bad news to a stakeholder and how you handled it",
            "what is the difference between leadership and management, and which do you excel at",
            "walk me through how you would plan a complex project if assigned it on your first week",
            "how do you balance speed with quality when both deadlines and standards are extremely demanding",
        ],
        5: [
            "Describe a time you introduced a change that met resistance: what did you measure, how did you persuade, and what was the quantified outcome six months later?",
            "If I gave you 3 conflicting priorities from 3 different managers, all due today, walk me through exactly how you would resolve the conflict and communicate your decision.",
            "Tell me about a failure that cost your team real time or money, what root cause you identified, and the system you put in place to prevent it from recurring.",
            "How do you evaluate whether a tool you have never used is right for a problem, and what is your lightweight process for validating it before committing?",
            "Give me an example of mentoring someone: what specific skill they gained, what you measured, and how the relationship changed your own strengths.",
            "Explain the most complex system you have ever worked on to a non-technical executive in under two minutes, and tell me what you learned from doing so.",
        ],
        6: [
            "The behavioral interview method asks for stories with real specificity: past behavior predicts future results, so interviewers probe for the situation, the task, the action, and the outcome; candidates who prepare 3 quantified stories about different strengths answer 60% more convincingly than those who improvise on the spot.",
            "When asked about salary expectations, the strongest candidates anchor with research: they state a single number tied to market data, then shift the conversation to value, leaving the negotiator something to move toward; studies across 9 industries show anchored candidates secure median offers 5.4% higher than those who state a range.",
            "Hiring managers consistently name curiosity as the most underrated attribute: candidates who ask questions about the product, the team, and the roadmap during their interview signal engagement, and 78% of interviewers report that the question round — not the answer round — tipped their final decision.",
            "The 'tell me about yourself' question is a positioning opportunity, not a biography: the best answers compress education, the past two roles, and the current ambition into 90 seconds, ending precisely where the role being interviewed begins.",
            "For technical roles, whiteboard problems test communication as much as code: the top quartile of candidates explain their approach aloud, consider edge cases, and state assumptions before writing a single line, while struggling candidates code silently and discover their assumptions only in the tests.",
            "Cultural-fit interviews evaluate alignment with values rather than skills: answers weigh should scenarios in terms of how the candidate reasons, not what they conclude, which is why rehearsed corruption stories fail and honest dilemma narratives succeed.",
        ],
        7: [
            "The STAR method structures every behavioral answer in four beats — Situation, Task, Action, Result — and interviewers trained on it report that structured responses receive 34% higher ratings than unstructured ones, because evaluators can isolate exactly which element of a candidate's past behavior demonstrates the competency at stake.",
            "Salary negotiation follows a measured sequence: know your market number from two sources, let the interviewer mention a figure first, reframe once around your measured value, and pause 5 seconds after your counteroffer; candidates who pause reported 8% better final packages than those who filled the silence.",
            "When answering 'What is your biggest weakness,' the key is calibration, not confession: top performers name a real, minor weakness, describe the concrete system they built to mitigate it, and present evidence the system works — a framing that reads as self-awareness rather than self-sabotage.",
            "Behavioral interviews trust specificity over polish: candidates who recalled 3 concrete metrics (a 21% revenue lift, a 40% faster pipeline, a 2-month schedule saved) were rated twice as credible as peers making equivalent claims without numbers, because metrics convert assertion into evidence an interviewer can verify.",
            "The opening 90 seconds of an interview predicts 71% of the final rating: first impressions set expectations that anchors subsequent evaluation, which is why the strongest candidates rehearse their introduction, arrive with a notebook and 3 prepared questions, and match the interviewer's pace rather than racing to impress.",
            "Case interviews, common in consulting, reward structure over speed: a framework — markets, costs, risks, and feasibility — communicated before any calculation earns most of the points, because interviewers grade the reasoning pathway, not the arithmetic answer; 90% of Web-scale case failures come from head-first computation.",
        ],
        8: [
            "Panel interviews expose consistency gaps that one-on-one rounds hide: a candidate who is engaging with a single interviewer often replies with radically different energy to each of 4 panelists, and inter-rater scoring studies show that panels reward candidates who made eye contact with every member and adjusted complexity to the questioner's discipline.",
            "The 'What questions do you have?' round is graded: candidates who ask about growth, teammates, and honest constraints score 27% higher than those who ask nothing or only about compensation, because questions about substance reveal that the candidate is evaluating the fit, not merely auditioning for it.",
            "Preparing with mock interviews that record video produces measurable gains: candidates who reviewed and self-corrected 3 recorded mock rounds reduced filler words by 48% and hesitation pauses by 31%, a coaching effect that undisclosed interviews perversely train for better than any scripted preparation can.",
            "Competency frameworks used by large employers grade candidates on 8 to 12 behaviors such as 'Influencing without Authority' and 'Learning Agility'; successful candidates map each planned story to at least one competency and, crucially, verify that the story's lesson matches the competency's behavioral anchors before entering the room.",
            "Background interviews, the second most common method after structured ones, ask former colleagues to rate a candidate on the same competencies; candidates who maintained anyone can call me relationships during employment earned average reference ratings 1.3 points higher on a 5-point scale, a reminder that reputation is built in the years before it is needed.",
            "The 'greatest failure' question separates candidates who own outcomes from those who deflect: interviewers specifically listen for the pronoun 'I' over 'we,' a timeline that does not jump ahead, and a preventive system — not a resolve — as the resolution; candidates who named an error they themselves introduced received higher resiliency scores than those who blamed teams.",
        ],
        9: [
            "The offer-decision science is blunt about negotiation: accept now, and you leave on the table an estimated 5% to 11% of value; the standard advice queue is to ask for one week, research three data points, and counter with a single justification tied to demonstrated performance, since multi-reason counters predictably weaken — a pattern confirmed across 6 negotiation studies in the last 5 years.",
            "When structured interviews are administered identically, they predict job performance about twice as well as unstructured conversation (validity of 0.51 versus 0.24); knowing this, ambitious candidates ask in advance whether the interview is structured, then map every answer to the published competencies, converting evaluation mechanics into preparation advantage.",
            "Candidate evaluation can be gamed by availability bias: interviewers recall the most recent, vivid, or emotional answers, so the final candidate in the day receives roughly 5% higher raw scores; candidates who understand the schedule slot their strongest story near the end and let their weakest material open the conversation.",
            "The 'sell me a pen' exercise, iconic in sales interviews, is actually a listening test: the top responses ask what the interviewer means by pen, who the buyer is, and which single feature lands the deal, then tailor the pitch to that answer — a framework that wins 84% of judged first trials against product-dump responses.",
            "Culture-fit scores stabilize in the first 5 minutes, so candidates who mirror the room deliberately — matching note-taking, energy, and formality while keeping their substance — post interrater-reliability scores 0.4 higher than those who bulldoze with personality; the aim is calibration, not imitation, and interviewers detect the difference.",
            "First-though rejection data shows why structured scoring exists: recruiters discount a candidate by 0.5 standard deviations the moment they hear a dialect or grammar pattern they personally dislike, a bias present even in trained panels; candidates preempt it by matching the interviewer's vocabulary density and pacing — readability adaptation, not identity concealment — which measurably closes hiring-inequality gaps in 19 replication studies.",
        ],
        10: [
            "The strongest negotiating lever in salary discussion is the BATNA — best alternative to a negotiated agreement: candidates who secured a competing offer secured, in industrial studies, an average 11.6% premium over their initial ask, while those who negotiated without an alternative landed within 2.1% of the first number; the preparation, not the chested courage, sets the ceiling.",
            "Lying to any direct question, including 'Do you have experience with X?', destroys votes across every scoring rubric that hiring teams use; honest 'I have transferable skills,' anchored with two quantified parallels, scores 3.2/5 on average versus 2.1/5 for embellished claims — because referees detected discrepancies in 71% of inflated interviews within 15 minutes and weighted the lapse across all future answers.",
            "The meta-study of 44 selection experiments isolates one interview question that beats the rest: asking candidates for the single past event they are most proud of, with follow-up probes on their contribution, predicts tenure better than personality inventories on their own, because pride elicits unscripted, non-performing-role answers that reveal authentic work identity.",
            "So-called 'stress interviews,' designed to push a candidate with interruptions and silence, have lost favor among employers as evidence mounted that they select for nervous systems rather than skills; top performers in these sessions reframe mechanics (pausing, summarizing the last question, returning to the backlog) — control behaviors that 2024's largest interviewer study correlated with offers, even in deliberately hostile rooms.",
            "The final ask — 'Do you have any other questions about us?' — is graded as the last data point on the rubric: asking to meet the team you will join, probing the first 90-day metric of the role, and verifying the team's definition of done produces average recommendation scores 28% higher than closing with 'I think you covered everything,' a phrase interviewers across 5 industry surveys rate as their least favorite way to end.",
            "Rejection data shows persistence is quantifiable: candidates who followed up with a brief, personalized email of substance (not a check-in) were 2.3 times more likely to be reconsidered when a role reopened, and 63% of those reconsiderations ended in offers; the study's caution — the follow-up praising the interviewer's question with a fresh insight, never demanding feedback — defines the difference between a valuable addition and a nag.",
        ],
    },
}


def text_pool(category, level):
    pool = L.get(category, {}).get(level)
    if not pool:
        for fallback in L.values():
            if level in fallback and fallback[level]:
                return fallback[level]
    return pool or ["type with care and enjoy the journey"]


def pick_text(category, level, seed=None):
    rng = random.Random(seed) if seed is not None else random
    pool = text_pool(category, level)
    return rng.choice(pool)


def pick_daily_text(seed_date=None):
    day = seed_date or date.today()
    rng = random.Random(day.isoformat())
    category = rng.choice(CATEGORIES)
    level = rng.randint(3, 7)
    text = pick_text(category, level, seed=day.isoformat())
    return text, category, level